In [1]:
import numpy as np
arr1= ([4,5,6])
print(arr1)

[4, 5, 6]


In [5]:
print(type(arr1))

<class 'list'>


In [6]:
arr2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
print(arr2[2,1])

8


In [8]:
print(arr2.shape)

(3, 3)


In [10]:
arrC=np.arange(0,30,5)
arrC

array([ 0,  5, 10, 15, 20, 25])

In [11]:
import sys
print(sys.version)

3.13.9 | packaged by Anaconda, Inc. | (main, Oct 21 2025, 19:09:58) [MSC v.1929 64 bit (AMD64)]
